### ISSUE TITLE
How to Get Node Local Space?

### ISSUE THREAD

**Issue by XXxR4GALXxx** [bqqbarbhg/ufbx#13]
I am converting a 3ds max script to ufbx:
```
fn GetLocalTM obj =
(
    matLocal = copy obj.transform
    if obj.parent != undefined then
    (
        matLocal = obj.transform * ( inverse obj.parent.transform )
    )
    return matLocal
)
```
How to get a node local matrix? (like the code above?)

**Comment by bqqbarbhg** [comment]
In the `ufbx_node` structure (eg. `mesh->node` with `ufbx_mesh *mesh`) there is `ufbx_transform transform` and `ufbx_matrix to_parent` which both contain the local transformation in both translation/location/scale and 4x3 matrix forms.

**Comment by XXxR4GALXxx** [comment]
> In the `ufbx_node` structure (eg. `mesh->node` with `ufbx_mesh *mesh`) there is `ufbx_transform transform` and `ufbx_matrix to_parent` which both contain the local transformation in translation/location/scale and 4x3 matrix forms respectively.

Thanks for answering me 👍 

One question, how to move the object vertex to 0,0,0?
For Example:

The first vertex starts at `(6,143, 158,750, -8,687). How to make it start at 0,0,0?`

Thanks! :)

**Comment by bqqbarbhg** [comment]
The vertices should be defined in the local space of the mesh. There is a convenience function `ufbx_vec3 ufbx_transform_position(const ufbx_matrix *m, ufbx_vec3 v)` that you can use with for example `node->to_root` to transform vertices into the world space if that's what you're looking for.

**Comment by XXxR4GALXxx** [comment]
> The vertices should be defined in the local space of the mesh. There is a convenience function `ufbx_vec3 ufbx_transform_position(const ufbx_matrix *m, ufbx_vec3 v)` that you can use with for example `node->to_root` to transform vertices into the world space if that's what you're looking for.

Okie thanks!! :)

last question (i promise?!)

How to get bone ID by vertex ID? I am using this method, but it does not work for all cases.

```
struct BoneData get_bone_data(ufbx_mesh* current_mesh, size_t vertexID)
{
    struct BoneData result; result.boneID = 0xFF; result.weight = 0.0f;
    for (size_t i = 0; i < current_mesh->skins.size; i++)
    {
        ufbx_skin current_skin = current_mesh->skins.data[i];
        for (size_t w = 0; w < current_skin.num_weights; w++)
        {
            if (current_skin.indices[w] == vertexID) // this is ok?
            {
                result.boneID = get_bone_index(current_skin.bone);
                result.weight = (float) current_skin.weights[w];
            }
        }
    }
    return result;
}
```

**Comment by bqqbarbhg** [comment]
No problem, sorry for the lack of documentation and examples, I'll need to work on that!

Yes the `indices` and `weights` arrays in `ufbx_skin` map to bone influences over the mesh vertices. Note that multiple bones can affect a single vertex and your function finds only one of them.

**Comment by XXxR4GALXxx** [comment]
> No problem, sorry for the lack of documentation and examples, I'll need to work on that!
> 
> Yes the `indices` and `weights` arrays in `ufbx_skin` map to bone influences over the mesh vertices. Note that multiple bones can affect a single vertex and your function finds only one of them.

In my case, it would be 1 bone per vertex.

So is my function correct? 🤔

**Comment by bqqbarbhg** [comment]
In that case it looks correct, but potentially very slow as it's O(n) per vertex making it O(n^2) in total. If you have `BoneData vertexBones[]` you might want to directly write something like:

```c
void get_bone_data(ufbx_mesh* current_mesh, struct BoneData *results)
{
    for (size_t i = 0; i < current_mesh->skins.size; i++)
    {
        ufbx_skin current_skin = current_mesh->skins.data[i];
        uint32_t boneID = get_bone_index(current_skin.bone);
        for (size_t w = 0; w < current_skin.num_weights; w++)
        {
            uint32_t id = current_skin.indices[w];
            results[id].boneID = boneID;
            result[id].weight = (float) current_skin.weights[w];
        }
    }
}
```

**Comment by XXxR4GALXxx** [comment]
> In that case it looks correct, but potentially very slow as it's O(n) per vertex making it O(n^2) in total. If you have `BoneData vertexBones[]` you might want to directly write something like:
> 
> ```c
> void get_bone_data(ufbx_mesh* current_mesh, struct BoneData *results)
> {
>     for (size_t i = 0; i < current_mesh->skins.size; i++)
>     {
>         ufbx_skin current_skin = current_mesh->skins.data[i];
>         uint32_t boneID = get_bone_index(current_skin.bone);
>         for (size_t w = 0; w < current_skin.num_weights; w++)
>         {
>             uint32_t id = current_skin.indices[w];
>             results[id].boneID = boneID;
>             result[id].weight = (float) current_skin.weights[w];
>         }
>     }
> }
> ```

Okie :)

How to get the UV values ​​correctly?
```
for (size_t v = 0; v < current_mesh->num_vertices; v++) {
    ufbx_vec2 uv_pos = current_mesh->vertex_uv.data[v];
    // uv_pos is wrong 🤔 
}
```
