### ISSUE TITLE
Mapping UV's to vertices

### ISSUE THREAD

**Issue by Vawx** [bqqbarbhg/ufbx#25]
I'm pretty sure this is all coming down to be not understanding the data / api well enough. Any help would be appreciated.

I am using OpenGL and using a Element Array Buffer to keep track of indices for the vertices. 

My test cube has 8 vertices, 36 indices, 12 triangles, and 12 faces. The UV data has 36 indices. This is how I am currently pulling the data: 

```   mesh.uvs_size = uf_mesh->num_indices * sizeof(v2);
    mesh.uvs = a_alloc(mesh.normals_size,v2);
    for(s32 i = 0; i < uf_mesh->num_indices; ++i) {
        v2 uv = {};
        uv.x = uf_mesh->vertex_uv.data[uf_mesh->vertex_uv.indices[i]].x;
        uv.y = uf_mesh->vertex_uv.data[uf_mesh->vertex_uv.indices[i]].y;
        memcpy(&mesh.uvs[i], &uv, sizeof(v2));
    }
 ```

This data gets bound to a glsl location `layout(location = 1) in vec2 aTexCoords;`

Bound:

```   // uvs
    glGenBuffers(1, &obj.uv);
    glBindBuffer(GL_ARRAY_BUFFER, obj.uv);
    glBufferData(GL_ARRAY_BUFFER, mesh.uvs_size, &mesh.uvs[0], GL_STATIC_DRAW);
```
Called: 

```   // uvs
      glEnableVertexAttribArray(1);
      glBindBuffer(GL_ARRAY_BUFFER, o.uv);
      glVertexAttribPointer(1, 2, GL_FLOAT, GL_FALSE, 0, (void*)0);
```

Result: 

![image](https://user-images.githubusercontent.com/4406322/132248865-6269638b-85c5-4600-ae41-fe791e20ccbe.png)

**Comment by bqqbarbhg** [comment]
Hi, sorry for the lack of documentation, I'm currently working on it!
It's a bit confusing as you usually can't use the mesh vertex indices directly as an OpenGL index buffer as it will expect _all_ attributes to be indexed. With FBX however you can have indexed vertex positions and non-indexed UV data for example. If you want to support non-per-vertex attributes such as UVs you need to have a flat vertex buffer without indices where all the attributes are fetched in a consistent way:
```c
positions[ix] = uf_mesh->vertex_position.data[uf_mesh->vertex_position.indices[ix]];
uvs[ix] = uf_mesh->vertex_uv.data[uf_mesh->vertex_uv.indices[ix]];
normals[ix] = ufbx_ufbx_get_vertex_vec3(&uf_mesh->vertex_normal, ix); // Shorthand for above
```

**Optionally:** If you want to optimize and have indexed vertex buffers you'd need to manually deduplicate the vertices based on what attributes you care about, for example by having something like this (unfortunately in C++ as doing a C example with a map would be huge...):
```cpp
#include <string.h>
#include <vector>
#include <map>

struct Vector2 { float x, y; };
struct Vector3 { float x, y, z; };

struct Vertex {
    Vector3 position;
    Vector3 normal;
    Vector2 uv;

    // Need to have order for `std::map`
    bool operator<(const Vertex &rhs) const {
        return memcmp(this, &rhs, sizeof(Vertex)) < 0;
    }
};

struct Mesh
{
    std::vector<Vertex> vertices;
    std::vector<uint32_t> indices;
};

Mesh generate_indexed_vertex_buffer(ufbx_mesh *mesh)
{
    Mesh result;
    std::map<Vertex, uint32_t> index_mapping;

    for (size_t face_ix = 0; face_ix < mesh->num_faces; face_ix++) {
        ufbx_face face = mesh->faces[face_ix];

        // Triangulate the N-gon face
        size_t num_triangles = face.num_indices - 2;
        uint32_t indices[64];
        if (!ufbx_triangulate(indices, 64, mesh, face)) continue;

        // Iterate for each index in the triangulated face
        for (size_t i = 0; i < num_triangles * 3; i++) {
            uint32_t ix = indices[i];

            // Fetch the vertex attributes at the index
            ufbx_vec3 pos = mesh->vertex_position.data[mesh->vertex_position.indices[ix]];
            ufbx_vec3 nor = ufbx_get_vertex_vec3(&mesh->vertex_normal, ix); // Equivalent to above
            ufbx_vec2 uv = mesh->vertex_uv.data[mesh->vertex_uv.indices[ix]];
            Vertex vertex = {
                { (float)pos.x, (float)pos.y, (float)pos.z },
                { (float)nor.x, (float)nor.y, (float)nor.z },
                { (float)uv.x, (float)uv.y },
            };

            // Insert `vertex` to `index_mapping`, does not change value if it exists already
            auto pair = index_mapping.insert({ vertex, (uint32_t)result.vertices.size() });
            uint32_t index = pair.first->second; // The value from `index_mapping`
            bool was_inserted = pair.second; // `true` if the `insert()` added the new value

            // Add the results to the index/vertex arrays
            result.indices.push_back(index);
            if (was_inserted) { 
                result.vertices.push_back(vertex);
            }
        }
    }

    return result;
}
```

This is essentially the same step that for example [meshoptimizer](https://github.com/zeux/meshoptimizer) calls [`meshopt_generateVertexRemap()`](https://github.com/zeux/meshoptimizer#indexing) if you want to read more about it.

**Comment by Vawx** [comment]
Thank you very much for the detailed response. :D

I will implement this and see how the meshoptimizer : meshopt_generateVertexRemap() call works.

**Comment by bqqbarbhg** [comment]
Oh also, I have some documentation in the current working branch about the mesh data layout that might be of use:

https://github.com/bqqbarbhg/ufbx/blob/overhaul/ufbx.h#L566-L613

**Comment by Vawx** [comment]
I have been using the "overhaul" branch for the last few weeks, figuring it was more up to date than the "master" branch but didn't notice that in the header, thank you.

Also, success:

![image](https://user-images.githubusercontent.com/4406322/132257505-01005329-602d-4d4f-9b44-2be267efb292.png)

Will need to get rid of the dependency on the <vector> and <map> includes but this is a great first example.  👍

**Comment by bqqbarbhg** [comment]
Nice, glad it works!

And yea the overhaul has about twice the commits as the master at the moment, hopefully I can get the merge done soonish :D
