### ISSUE TITLE
Provide access to preRotation and postRotation components

### ISSUE THREAD

**Issue by DeCarabas** [bqqbarbhg/ufbx#27]
I need to do my own animation evaluation, and because the animations in the FBX tend to animate the euler angles directly, I need access to the pre- and post- rotation components of the transform, otherwise things come out all crooked-looking. :)

Right now I'm just using the internal interface, with `ufbxi_find_vec3`, like `ufbxi_get_transform` does, but still.

Also, I'm lucky that my pivots are all zero, but now that I think about it I probably need access to all that stuff too. :(

**Comment by bqqbarbhg** [comment]
I'm not sure yet how much of the low-level FBX format details I want to explicitly include in the header. I don't think there's a ton of value to re-expose existing `ufbx_props` values without any modification as if you need them you probably know the real property names already :D. I recently added user-facing property value fetch functions that can be used to simplify implementing custom low-level functionality (the internal `ufbxi_find_vec3()` only works with the fixed `ufbxi_SomeString` values).

So you could do something like this without depending on the internals:
```c
Transform get_transform(ufbx_node *node)
{
	// These could also come from `ufbx_evaluate_props()` or something
	ufbx_props *props = &node->props;

	ufbx_vec3 vec3_zero = { 0.0f, 0.0f, 0.0f };
	ufbx_vec3 vec3_one = { 1.0f, 1.0f, 1.0f };

	ufbx_vec3 scale_pivot = ufbx_find_vec3(props, "ScalingPivot", vec3_zero);
	ufbx_vec3 rot_pivot = ufbx_find_vec3(props, "RotationPivot", vec3_zero);
	ufbx_vec3 scale_offset = ufbx_find_vec3(props, "ScalingOffset", vec3_zero);
	ufbx_vec3 rot_offset = ufbx_find_vec3(props, "RotationOffset", vec3_zero);

	ufbx_vec3 translation = ufbx_find_vec3(props, "Lcl_Translation", vec3_zero);
	ufbx_vec3 rotation = ufbx_find_vec3(props, "Lcl_Rotation", vec3_zero);
	ufbx_vec3 scaling = ufbx_find_vec3(props, "Lcl_Scaling", vec3_one);

	ufbx_vec3 pre_rotation = ufbx_find_vec3(props, "PreRotation", vec3_zero);
	ufbx_vec3 post_rotation = ufbx_find_vec3(props, "PostRotation", vec3_zero);

	// WorldTransform = ParentWorldTransform * T * Roff * Rp * Rpre * R * Rpost * Rp-1 * Soff * Sp * S * Sp-1
	// NOTE: Rpost is inverted (!) after converting from PostRotation Euler angles
	Transform t = { ... };
	// User math functionality here to calculate the above with modifications...
	return t;
}
```

Additionally I'm thinking of a method that would let users override properties and evaluate the scene and transforms based on that but that's a long way into the future... The current API is more geared towards processing the FBX as more of a black box where for example a game asset processing pipeline would sample the node animation at a fixed rate with `ufbx_evaluate_transform()` and compress them without knowledge of the original FBX Euler angle curves.

**Comment by DeCarabas** [comment]
I agree, the more I think about it the more I think you're walking the correct line here.

**Comment by bqqbarbhg** [comment]
Probably not useful for your use case but inspired by this issue I figured out a neat API for overriding property values. I'm just going to explain it here to sketch some documentation, feel free to ignore if you wish :D

When evaluating animations you can pass a `ufbx_prop_override` list in:

```c
typedef struct ufbx_prop_override {
	// Element (`ufbx_element.id`) to override the property from
	// NOTE: You can get this from typed structs eg. `my_node->element.id`
	uint32_t element_id;

	// Property name to override.
	// Use `prop_namel.length = SIZE_MAX` for NULL-terminated strings.
	ufbx_string prop_name;

	// Override value, use `value.x` for scalars. `value_int` is initialized
	// from `value.x` if zero so keep `value` zeroed even if you don't need it!
	// Use `value_str.length = SIZE_MAX` for NULL-terminated strings.
	ufbx_vec3 value;
	ufbx_string value_str;
	int64_t value_int;

	// Internal: Gets filled automatically by `ufbx_prepare_prop_overrides()`
	uint32_t internal_key;
} ufbx_prop_override;

UFBX_LIST_TYPE(ufbx_const_prop_override_list, const ufbx_prop_override);

typedef struct ufbx_anim {
	ufbx_const_anim_layer_desc_list layers;

	// Override individual `ufbx_prop` values from elements
	// NOTE: Call `ufbx_prepare_prop_overrides()` to obtain this!
	ufbx_const_prop_override_list prop_overrides;

	bool ignore_connections;
} ufbx_anim;
```

Usage looks something like:

```c
ufbx_node *node = ufbx_find_node(scene, "pointLight1");
ufbxt_assert(node && node->light);
uint32_t element_id = node->light->element.id;

ufbx_prop_override overrides[] = {
	{ element_id, { "Intensity", SIZE_MAX }, { 10.0 } },
	{ element_id, { "Color", SIZE_MAX }, { 0.3, 0.6, 0.9 } },
	{ element_id, { "NewProp", SIZE_MAX }, { 10, 20, 30 }, { "Test", SIZE_MAX } },
};

// Make a copy of the default scene animation with our overrides
ufbx_anim anim = scene->anim;
anim.prop_overrides = ufbx_prepare_prop_overrides(overrides, ufbxt_arraycount(overrides));

ufbx_scene *state = ufbx_evaluate_scene(scene, &anim, 1.0f, NULL, NULL);
ufbxt_assert(state);
```

You can also substitute the values without specifying any animation by setting `ufbx_anim.layers.count = 0`. The overrides are supported by any function that takes in an `ufbx_anim` so you can for example evaluate a custom transform via `ufbx_evaluate_transform()`.
