### ISSUE TITLE
Question about animation curves.

### ISSUE THREAD

**Issue by grigoryoskin** [bqqbarbhg/ufbx#28]
Hi! 
Do I understand it correctly that curve array elements correspond to x,y,z components? 
https://github.com/bqqbarbhg/ufbx/blob/master/ufbx.h#L385

If so, how do I get a curve for a quaternion?

**Comment by grigoryoskin** [comment]
Ok, I did a little googling and it looks like FBX only has animation with Euler rotations.

**Comment by bqqbarbhg** [comment]
Hi! Yea the channels are in x,y,z order if it's a property where it makes sense (like translation/rotation/scale), I'll add a mention of that to the header to clear it up!

To my understanding (and all FBX files I have seen so far) FBX only supports Euler rotations properly. There _is_ an internal "spheric" rotation order which could be quaternion-ish but I have never seen a file that uses that. If you want to handle a variety of FBX you need to handle the `"RotationOrder"` property as well (see `ufbx_rotation_order`). It's not really nice to use in the `master` branch as you need to manually query the property, in the working `overhaul` branch it's accessible from `ufbx_node` directly.

**Comment by grigoryoskin** [comment]
I see, thank you!
