### ISSUE TITLE
Load is crashing

### ISSUE THREAD

**Issue by beckylum0216** [bqqbarbhg/ufbx#30]
Hi,

ufbnx_loadfile segfaults on file load. The error occurs on the allocation of a map pointer?
![image](https://user-images.githubusercontent.com/11342938/154404231-5769a616-3e7a-478e-86f4-34f1d4bde498.png)

The loader was loading this file.
[SK_EliteTrooper.zip](https://github.com/bqqbarbhg/ufbx/files/8085480/SK_EliteTrooper.zip)

Thanks.

**Comment by bqqbarbhg** [comment]
Hi! I tried to load the scene but couldn't reproduce the error. From your screenshot it looks like you're passing an `ufbx_load_opts` structure that is not zeroed. In C++ you should do something like:

```cpp
ufbx_error error; // This can be uninitialized
ufbx_load_opts opts = { };
ufbx_scene *scene = ufbx_load_file(path, &opts, &error);
```

**Comment by beckylum0216** [comment]
Thanks.
