### ISSUE TITLE
"metallic" should be "metalness"

### ISSUE THREAD

**Issue by Novum** [bqqbarbhg/ufbx#40]
`{ UFBX_MATERIAL_PBR_METALLIC, ufbxi_string_literal("metalness") },`

The term used in all PBR literature is "metalness" and I think this should be reflected in the ufbx API as well. Very confusing otherwise.

**Comment by bqqbarbhg** [comment]
Hi, coming from game development background most programs I'm used to call it "metallic" but I did a little survey from programs that I happen to have at hand as I try to name things by what they're called in content creation programs:

- Metalness: Maya, 3ds Max, Marvelous Designer
- Metallic: Blender, Unity, Unreal, Godot, Substance Painter

It's a bit of a mixed bag but I feel like most people using ufbx are/will be gamedev-adjacent so "metallic" is probably more familiar for the users.

**Comment by bqqbarbhg** [comment]
Actually thinking about it later "metalness" might be better as now the PBR map names match the OSL standard surface which is the de-facto standard physical shading model in FBX. Well there's still `roughness` (ufbx) vs `specular_roughness` (OSL) but that goes too far in my book :D
