### ISSUE TITLE
ufbx_assert unused variable warning

### ISSUE THREAD

**Issue by Trider12** [bqqbarbhg/ufbx#46]
In the file `ufbx.c` there is this snippet of code, starting on the line 18846:

```cpp
// Build a KD-tree out of the collected reflex vertices.
uint32_t num_skip_indices = (1u << (UFBXI_KD_FAST_DEPTH + 1)) - 1;
uint32_t kd_slow_indices = num_kd_indices > num_skip_indices ? num_kd_indices - num_skip_indices : 0;
ufbx_assert(kd_slow_indices + face.num_indices * 2 <= num_indices);
ufbxi_kd_build(nc, kd_indices, kd_tmp, num_kd_indices, 0, 0, 0);
```

The problem is that in the `Release` build `ufbx_assert` is reduced to nothing, so the variable `kd_slow_indices` becomes unused, and the compiler generates a warning. And because the project I'm currently working on uses `/WX` and `-Werror` compiler flags the warning becomes an error.

I understand that fixing warnings is not a high priority, but [here](https://stackoverflow.com/questions/777261/avoiding-unused-variables-warnings-when-using-assert-in-a-release-build) are a couple of ways to deal with disappearing asserts.

**Comment by bqqbarbhg** [comment]
Thanks for the issue! I try to compile code with the strictest reasonable warnings on CI, but seems like I'm missing a permutation that compiles with Release+Werror.

**Comment by bqqbarbhg** [comment]
Whew looks like GitHub interpreted "should fix" as "fixes", I'll keep this open if you want to verify it. If not feel free to close the issue!

**Comment by Trider12** [comment]
Thanks! I've tested on `MSVC` with `/W4 /WX` and on `Clang` with `/-Wall -Werror` in both `Release` and `Debug` and there are no warnings.
