### ISSUE TITLE
Wrong orientation

### ISSUE THREAD

**Issue by bztsrc** [bqqbarbhg/ufbx#49]
Hi,

I'm trying to use your awesome library, but I run into a slight problem. It looks like the axis are swapped. I've examined your example viewer's code (which works correctly), but couldn't pinpoint what I'm missing.

Currently my code looks like this:
```c
    ufbx_load_opts opts = { 0 };
    ufbx_error error = { 0 };
    ufbx_scene *scene = NULL;

    opts.load_external_files = true;
    opts.allow_null_material = true;
    opts.evaluate_skinning = true;
    opts.target_axes.right = UFBX_COORDINATE_AXIS_POSITIVE_X;
    opts.target_axes.up = UFBX_COORDINATE_AXIS_POSITIVE_Y;
    opts.target_axes.front = UFBX_COORDINATE_AXIS_POSITIVE_Z;
    scene = ufbx_load_memory((const void*)data, size, &opts, &error);
```
Just for curiousity, I've tried this
```diff
-    opts.target_axes.up = UFBX_COORDINATE_AXIS_POSITIVE_Y;
+    opts.target_axes.up = UFBX_COORDINATE_AXIS_NEGATIVE_Y;
```
but nothing changed, the loaded model is still upside-down. So I'm guessing I might miss a flag telling ufbx to actually apply target_axis conversion maybe? FYI, I don't use the data as-is, I call `ufbx_triangulate_face` if that matters (but so does your viewer.c, so I don't think that's the reason).

What am I missing? My full code is [here](https://gitlab.com/bztsrc/model3d/-/blob/master/m3dconv/fbx.h) if you want to take a look. I'm working on a model converter, which currently uses assimp, but that library is very buggy so I'd like to replace that with ufbx.

Thanks,
bzt

**Comment by bqqbarbhg** [comment]
Thanks for the kind words! The documentation is still lacking so it's a bit unclear but the `target_axes` doesn't affect the actual mesh geometry, but rather the root node transform (ie. `ufbx_scene.root_node.local_transform` and derived properties). If you plan to propagate the scene graph (derived from `ufbx_node`s that contain the meshes) then the orientation should come through that.

However if you just want flat mesh data without bothering with any transformations you can transform the vertices to world space with some ufbx utilities:

```c
ufbx_node *node = mesh->instances.data[0];

// for (materials) for (faces) for (tris)
{
    pos = ufbx_get_vertex_vec3(&mesh->vertex_position, tri_indices[3 * vi + i]);

    // Transform from local space to world space
    pos = ufbx_transform_position(&node->geometry_to_world, pos);

    m3d->vertex[m3d->numvertex].x = pos.x;
    m3d->vertex[m3d->numvertex].y = pos.y;
    m3d->vertex[m3d->numvertex].z = pos.z;
}

// There's also an utility function to get a matrix that can correctly
// transform normals, as you probably want to transform them too:
ufbx_matrix normal_to_world = ufbx_matrix_for_normals(&node->geometry_to_world);

// for (materials) for (faces) for (tris)
{
    normal = ufbx_get_vertex_vec3(&mesh->vertex_normal, tri_indices[3 * vi + i]);

    normal = ufbx_transform_direction(&normal_to_world, normal);

    // Normalize the length to 1 (maybe this could be an utility function in the future..)
    ufbx_real length = sqrt(normal.x*normal.x + normal.y*normal.y + normal.z*normal.z);
    normal.x /= length;
    normal.y /= length;
    normal.z /= length;

    m3d->vertex[m3d->numvertex].x = normal.x;
    m3d->vertex[m3d->numvertex].y = normal.y;
    m3d->vertex[m3d->numvertex].z = normal.z;
    m3d->vertex[m3d->numvertex].w = 1.0;
}
```

The above `mesh->instances.data[0]` is a bit unsafe as meshes may be contained in more than one nodes (ie. duplicated objects with different transforms but with same mesh data) or in some rare files maybe even have zero instances. One safe way to handle that is to iterate over all the instances in a mesh like:

```c
// Iterate through all meshes (unique geometries) in the file
for(i = 0; i < scene->meshes.count; i++) {
    ufbx_mesh *mesh = scene->meshes.data[i];

    // Iterate over all the instances (clones of the geometry)
    for(j = 0; j < mesh->instances.count; j++) {
        ufbx_node *node = mesh->instances.data[j];

        // Process instance of `mesh` transformed at `node`
        read_mesh(m3d, mesh, node);
    }
}
```

**Comment by bztsrc** [comment]
Thank you very much for your detailed answer! It helps a lot!

> However if you just want flat mesh data without bothering with any transformations

I'm not entirely sure I follow. I need the mesh in world space with unique vertices sure (bind-pose), but I also need the bones (hierarchical list of transformations, parent+translation+rotation triplets), and a skin (which vertex belongs to which bone by what weight).

If I use this "flattening" (specially with duplicated objects with different transforms as you've pointed out), wouldn't I loose the skin relation? Are there transformations other than the bone transformations?

Thank you,
bzt

**Comment by bqqbarbhg** [comment]
Yea that's where it gets a bit more complex, the core of the issue is exactly with your question:

> Are there transformations other than the bone transformations?

If the mesh is not bound to a skin it moves with it's parent node (you can think of this as the whole mesh being parented to a bone that is the node it's contained within). So you really want to do that transformation only for meshes that are not skinned, for skinned meshes you want to use the raw geometry space vertices and `ufbx_skin_cluster.geometry_to_bone` combined with the run-time bone transforms.

For the animations you can get the `ufbx_evaluate_transform()` utility function to resample the animation at a specific point in time without having to bother with the animation curves.

**Comment by bztsrc** [comment]
Hi,

Thank you again for your help!

> If the mesh is not bound to a skin it moves with it's parent node (you can think of this as the whole mesh being parented to a bone that is the node it's contained within). So you really want to do that transformation only for meshes that are not skinned, for skinned meshes you want to use the raw geometry space vertices and ufbx_skin_cluster.geometry_to_bone combined with the run-time bone transforms.

Not sure I understand this. Maybe an example would be useful. Let's assume we have a model of a walking man. There's only one leg mesh stored, but with two instances. Obviously for a walking cycle, these two instances must belong to different bones. How would this be represented in the data?

> For the animations you can get the ufbx_evaluate_transform() utility function to resample the animation at a specific point in time without having to bother with the animation curves.

Thanks, but that's not good for me. What I need is a bind-pose skeleton, and for each animation a series of timestamp and skeleton pairs (where this latter skeleton has exactly the same number of bones in the same order as the bind-pose, and timestamps can be at arbitrary intervals). I need the bones in this format because I've already implemented a pretty sophisticated and complex compression algorithm that calculates and stores only the bones that have changed compared to the previous frame's parent bone relative space. Huh, I know, sounds pretty complicated. The point is, the in-memory representation has to be a series of entire skeletons for each animation, and my M3D SDK takes care of the rest compression-wise.

Thanks,
bzt

**Comment by bztsrc** [comment]
> Thanks, but that's not good for me.

I take this back. If I can get a list with timestamps  of keyframes defined in the model, then I can use that list to render the skeleton at those specific times. I only have to convert the bones back from world space into bone relative space to get exactly what my SDK needs. Is this what you meant?

Cheers,
bzt

**Comment by bqqbarbhg** [comment]
Heya!

> There's only one leg mesh stored, but with two instances. Obviously for a walking cycle, these two instances must belong to different bones. How would this be represented in the data?

FBX doesn't support skinning and instancing at the same time as far as I know, at least not in any of the files I've seen. (Technically: the skin deformer containing the bones and weights is attached to the *geometry*, not an instance). So what I do for example in one of my importers is to transform non-skinned meshes based on their parent transforms and ignore the transforms of skinned meshes.

> I only have to convert the bones back from world space into bone relative space to get exactly what my SDK needs. Is this what you meant?

Yes and you don't even need to convert them! `ufbx_evaluate_transform()` gives you the transform in local space, maybe the function could be named a bit better.. You could also interpret the animation keyframes from the curves yourself but be warned that getting the `local_transform` from the FBX properties [is a bit hairy](https://github.com/bqqbarbhg/ufbx/blob/df8d5d6fccac23a5a0ae5382bd0047005fc6fb24/ufbx.c?ts=4#L14800-L14836), at least if you want to do it "properly". So that's why I recommend resampling the bone animations with the utility function with a fixed framerate.

**Comment by bztsrc** [comment]
Thank you so much!

> FBX doesn't support skinning and instancing at the same time as far as I know, at least not in any of the files I've seen. 

That's very helpful!

> Yes and you don't even need to convert them! ufbx_evaluate_transform() gives you the transform in local space, maybe the function could be named a bit better..

Perfect! Don't worry about the naming, you should focus on writing a bit more docs instead ;-) Seriously, your lib is awesome!

> You could also interpret the animation keyframes from the curves yourself but be warned that getting the local_transform from the FBX properties is a bit hairy, at least if you want to do it "properly".

That much I've figured, so it's great to have a utility function that does all of the transformations for me.

> So that's why I recommend resampling the bone animations with the utility function with a fixed framerate.

Fixed framerate and resampling is a no-go for me. I'm not implementing a viewer, but a converter, so I definitely need the exact keyframes the original model had. (Fixed framerate can easily result in huge storage overhead in the output without any benefit.)

Anyway, thank you again, I'll close this issue now because I got answers to all my questions! I hope you don't mind if I turn to you with further technical questions should I run into some non-trivial issues in the future. Thanks for all the help so far, I really appreciate it!

Cheers,
bzt
