### ISSUE TITLE
SIGBUS (signal SIGBUS: illegal alignment)

### ISSUE THREAD

**Issue by heitaoflower** [bqqbarbhg/ufbx#9]
Hi, friend,

I encountered a crash issue when I try to use your ufbx to parse fbx in my personal project.

On the PC platform either 32bit or 64bit are running swimmingly.

however on the android platform-armv7a, crash.

by armv8a-64bit is ok.

here is the concrete code snippet:

`vals[i].i = (int64_t)(vals[i].f = ufbxi_read_f64(data + 1));`

**Comment by bqqbarbhg** [comment]
Hey, sorry I missed the issue. Unaligned loads were on my TODO-list and I pushed a fix now if you're still interested!

**Comment by limdingwen** [comment]
For reference: Add `#define UFBX_NO_UNALIGNED_LOADS` to the top of ufbx.c.

**Comment by bqqbarbhg** [comment]
This issue has been fixed and that should not be necessary as unaligned loads are enabled only on x64/ARM64 that support them.

However if you do use some trapping mode then that define is necessary.

**Comment by limdingwen** [comment]
Ah, that might be why. I was compiling with fsanitize=address,undefined.

**Comment by bqqbarbhg** [comment]
@limdingwen Ah yes that was a real issue. I have a lot of UBsan fixes over at [`overhaul`](https://github.com/bqqbarbhg/ufbx/tree/overhaul), hopefully getting that merged soon to `master`.

https://github.com/bqqbarbhg/ufbx/blob/3f0899b9ee2717bc85186856af381963583337ca/ufbx.c#L87-L100
